### ISSUE TITLE
Late Commit on not prepared instance 

### ISSUE THREAD

**Issue by nivBlox** [bloxapp/ssv-spec#106]
**Issue:**
In case where we got decided for instance (without getting propose) and then got late commit (4th signer) it will fail cause of missing proposal for round. 

**Fix:**
 need to check in validation if already got decided and if so validate the 4th signer commit

**TODO**
Need to uncomment those tests - 
1, LateCommitNoInstance
2, LatePrepareNoInstance

**Comment by alonmuroch** [comment]
It's a special case, is it worth adding?
What will happen is that peers will get the 4th decided and broadcast it

**Comment by GalRogozinski** [comment]
Even though @alonmuroch is right it is still an issue. Shouldn't we fix it?

**Comment by GalRogozinski** [comment]
No one answered me and I actually agree with Alon so I am closing this
