### ISSUE TITLE
Future decide with no running instance panic

### ISSUE THREAD

**Issue by olegshmuelov** [bloxapp/ssv-spec#235]
when there is no running instance and we try to check if the future msg decided correctly we will get a panic (attack vector).
https://github.com/bloxapp/ssv-spec/blob/b8be13458287f1099a8edfd8115d0814eb85fb2f/ssv/runner.go#L191

solution:
check `RunningInstance` for nil
```go
decidedRunningInstance := decided && b.State.RunningInstance != nil && decidedMsg.Message.Height == b.State.RunningInstance.GetHeight()
```

add tests for specific scenario for all related duty runners

btw the implementation has the `nil` check

**Comment by GalRogozinski** [comment]
@olegshmuelov 
now that #300 removed future message you think this is an issue?
I can add the nil check but not sure if there are relevant tests
