### ISSUE TITLE
 Inaccurate instance bumping behavior

### ISSUE THREAD

**Issue by olegshmuelov** [bloxapp/ssv-spec#266]
A potential issue has been identified with the way instances progress to the next height. When an instance advances, it is observed that the start value from the previous height is being used. This behavior is seen in the code snippet from the decided_sc.go file (path: ssv-spec/ssv/spectest/tests/runner/duties/newduty), specifically in the lines 71 to 81.
https://github.com/bloxapp/ssv-spec/blob/6ef950c1f89e086d8eab65108cb41e98c463cb0e/ssv/spectest/tests/runner/duties/newduty/decided_sc.go#L71-L81

Furthermore, questions have been raised about the sequence of operations for the Attester and SyncCommittee roles in the context of the PostDecided test. It is unclear why the height of an instance is incremented before the completion of the runner state (Finished=True).

This issue is currently classified as a bug, as these observations suggest potential inconsistencies in the instance bumping procedure and the execution order in the PostDecided test.

**Comment by GalRogozinski** [comment]
1. It looks like the `startValue` simply comes from this line:
https://github.com/bloxapp/ssv-spec/blob/d3d12cffe023d956feec29c4eb074b9fff928503/ssv/sync_committee.go#L169

It doesn't inherit it from previous height. It is just a function of the slot we are using.

2. Once an instance is decided. A new instance can be created. The 2 duties in question (Attester and SyncCommittee) don't have a precon phase. This is why an instance starts as soon as the runner starts.
