### ISSUE TITLE
Join commit and post-consensus

### ISSUE THREAD

**Issue by MatheusFranco99** [bloxapp/ssv-spec#302]
In commit, we sign the encoded Message structure.
In post-consensus, we sign the decided data.

If the probability of a QBFT round being successful is high, a good optimisation would be to append to the commit message a partial signature over the data (since we'll try to reach quorum and, if this is the case, we'll be able to create the validator signature, as in the post-consensus phase).

The protocol latency is determined by the message processing time and message transmission delay (basically). This doesn't improve much processing time, but reduces message transmission delay.

Thus, if message transmission delay is a bottleneck of the protocol performance, the optimisation is strongly encouraged.

**Comment by TinyVege** [comment]
i want to ask: "post-consensus" means when an operator node receives quorum(2t+1) commit messages, right?

**Comment by MatheusFranco99** [comment]
Hey @TinyVege! Yes, the post-consensus phase starts after the consensus ends, i.e. after it receives a quorum of commit messages. More precisely, the post-consensus phase is the phase of the duty execution that collects signatures over the agreed object and reconstructs the validator signature to broadcast the signed beacon object to the blockchain through a beacon service.

**Comment by TinyVege** [comment]
thanks, i get it.
And would you have a look at my issur #351 😄 @MatheusFranco99
