### ISSUE TITLE
How to identify the Operator Consensus Breakdown

### ISSUE THREAD

**Issue by TinyVege** [bloxapp/ssv-spec#364]
![image](https://github.com/bloxapp/ssv-spec/assets/106942308/006fa9fd-b5f7-4843-8e21-b0f8909200ac)
**Fact:** In slot 8423656, operator id = 3 is breakdown

Here are some questions:
1. How is "breakdown" defined? Is it an operator going offline or sending messages that differ from those of the quorum nodes, or something else?
2. What evidence proves that operator id = 3 is in breakdown? Is it through protocol messages generated in the consensus at slot 8423656, or is it a additional  round of consensus specifically for the breakdown?
3. After obtaining the evidence, who adjudicates the result?

Hope anybody help me with description or code!!❤❤💨🍗🍗🍗

**Comment by GalRogozinski** [comment]
For questions about the explorer, please go to discord
