### ISSUE TITLE
Blinded blocks support

### ISSUE THREAD

**Issue by alonmuroch** [bloxapp/ssv-spec#67]
Should the contract indicate if the operators sign blinded blocks or regular blocks?

**Comment by alonmuroch** [comment]
@lior-blox does it require an SIP?

**Comment by lior-blox** [comment]
@alonmuroch yes.

**Comment by alonmuroch** [comment]
@lior-blox I'll leave it to you

**Comment by alonmuroch** [comment]
@moshe-blox SIP https://github.com/bloxapp/SIPs/pull/20
